### PR TITLE
fix: ASSEMBLY - `openExternalLinksInDifferentTab` interferring with cookiebot

### LINKED ISSUE #28: [Task]: fix `openExternalLinksInDifferentTab` interferring with cookiebot
https://discord.com/channels/397872799483428865/1090642339669745745/1090642571631538186

It seems like that function is adding the `target="_blank"` to the cookiebot banner, only reproduceable in firefox, which opens a new tab every time the user interacts with cookiebot. It seems to be happening on shimmer & assembly blogs, not in iota, not sure why, but we should try to mitigate in all blogs 🙏🏼 and even the main iota website which I think has something similar

### PR DESCRIPTION
**Pull request by evavirseda**
Closes #28

### CODE REVIEW

File: src/js/app.js [hunk 1]
```diff
@@ -179,13 +179,20 @@ $(() => {
...
     })
+
     const openExternalLinksInDifferentTab = () => {
-        let links = $('a')
-        $.each(links, function(index, value) {
-            if (!value.href.includes(window.location.hostname)) {
-                value.target = '_blank'
-            }
-        })
+        () => {
```
Comment (begonaalvarezd) [inline src/js/app.js]: I believe this `() => {` is reduntant

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]
🚀
